apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbserver
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql
  nfs:
    path: /file_share
    server: 10.254.194.120
