
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: ec95c258266b8e985848cae688effa2b
        image: mysql:5.5
        imagePullPolicy: ""
        name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
status: {}
