apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
status: {}
