apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbserver
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /nfs_share
    server: 10.254.194.122
