apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.name.mysql }}
  name: {{ .Values.name.mysql }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.name.mysql }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Values.name.mysql }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.value }}
        image: mysql:5.5
        imagePullPolicy: ""
        name: {{ .Values.name.mysql }}
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
status: {}
