apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.name.mysql }}
  name: mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: dbserver
  resources:
    requests:
      storage: 5Gi
status: {}
